config/routes.rb
Rails.application.routes.draw do
  
  resources :replies, except: [:index]
  resources :comments, except: [:index], path: 'discussion'
  devise_for :users
  resources :features, except: [:index]
  root 'videos#index'
  resources :artists
  resources :videos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @replies = Reply.all
  end

  def show
  end

  def new
    @reply = Reply.new
  end

  def edit
  end

  def create
    @reply = Reply.new(reply_params)
    @reply.user_id = current_user.id

    respond_to do |format|
      if @reply.save
        format.html { redirect_to video_path(@reply.comment.video_id), notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to video_path(@reply.comment.video_id), notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to video_path(@reply.comment.video_id), notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_reply
      @reply = Reply.find(params[:id])
    end

    def reply_params
      params.require(:reply).permit(:comment_id, :user_id, :body)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_with(model: reply, local: true) do |form| %>
  <% if reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment_id %>
    <%= form.text_field :comment_id, id: :reply_comment_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :reply_user_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.trix_editor :body, id: :reply_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Replies</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.comment %></td>
        <td><%= reply.user %></td>
        <td><%= reply.body %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @reply.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @reply.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @reply.body %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>