config/routes.rb
Rails.application.routes.draw do
  
  resources :replies, except: [:index]
  resources :comments, except: [:index], path: 'discussion'
  devise_for :users
  resources :features, except: [:index]
  root 'videos#index'
  resources :artists
  resources :videos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
    is_impressionable
    
    has_attached_file :avatar, styles: { 
        large: "500x500>",
        medium: "300x300>", 
        small: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    has_many :features, dependent: :delete_all

    def self.select
        Artist.order("stage_name").map { |s| 
            [
                s.stage_name,
                s.id
            ]
        }
    end

    def full_name
        "#{self.first_name + "  " +self.last_name}"
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  impressionist action: [:show]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @artists = Artist.all
  end

  def show
    @features = @artist.features.order("created_at DESC")
    @videos = Video.where(id: @artist.features)
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:first_name, :last_name, :stage_name, :birth_place, :birth_date, :bio, :active_status, :active_from, :active_to, :avatar)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :avatar%>
    <%= form.file_field :avatar, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control', id: :artist_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control', id: :artist_last_name %>
  </div>

  <div class="field">
    <%= form.label :stage_name %>
    <%= form.text_field :stage_name, class: 'form-control', id: :artist_stage_name %>
  </div>

  <div class="field">
    <%= form.label :birth_place %>
    <%= form.text_field :birth_place, class: 'form-control', id: :artist_birth_place %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.text_field :birth_date, class: 'form-control', type: 'date', id: :artist_birth_date %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, class: 'form-control', id: :artist_bio %>
  </div>

  <div class="field">
    <%= form.label :active_status %>
    <%= form.text_field :active_status, class: 'form-control', id: :artist_active_status %>
  </div>

  <div class="field">
    <%= form.label :active_from %>
    <%= form.text_field :active_from, class: 'form-control', id: :artist_active_from %>
  </div>

  <div class="field">
    <%= form.label :active_to %>
    <%= form.text_field :active_to, class: 'form-control', id: :artist_active_to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Stage name</th>
      <th>Birth place</th>
      <th>Birth date</th>
      <th>Bio</th>
      <th>Active status</th>
      <th>Active from</th>
      <th>Active to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.first_name %></td>
        <td><%= artist.last_name %></td>
        <td><%= artist.stage_name %></td>
        <td><%= artist.birth_place %></td>
        <td><%= artist.birth_date %></td>
        <td><%= artist.bio %></td>
        <td><%= artist.active_status %></td>
        <td><%= artist.active_from %></td>
        <td><%= artist.active_to %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>New Artist</h1>        
            <%= render 'form', artist: @artist %>
            <%= link_to 'Back', artists_path %>
        </div>

        <div class="col-md-6">
        </div>
    </div>
</div>

app/views/artists/show.html.erb
<div class="container">

<div class="row">
  
  <div class="col-md-4">
    <div class="user_profile">
      <div class="cover_photo" style=" background-image: url(<%= @artist.avatar.url(:large)%>);">        
      </div>

      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h3><%= @artist.stage_name %></h3>
            <%= @artist.full_name %>
          </div>
          <div class="col-md-5 text-align-right">
            <h4><%= @artist.impressionist_count %></h4>
            VIEWS
          </div>
        </div>

      </div>
    </div>

    <br> <br>

    <% if @artist.birth_place.length > 2 %>
    
      <p>
        <strong>Birth place:</strong>
        <%= @artist.birth_place %>
      </p>

    <% end %>

    

    <% if @artist.birth_date.length > 2 %>
      <p>
        <strong>Birth date</strong> <br>
        <%= @artist.birth_date %>
      </p>
    <% end %>

    <p>
      <%= @artist.bio %>
    </p>

</div>

<div class="col-md-8">

<div class="video_list">
    
    
    <% @features.each do |v| %>
      <a href="<%= video_path(v.video_id)%>">
        
        <div class="video_item">
          <div class="item_cover" style=" background-image: url(<%= v.video.media.url(:thumb) %>);">
          </div>
          <div class="item_info">
            <%= truncate(v.video.title, length: 30) %>
          </div>
        </div>
            
      </a>
    <% end %>
  </div>

</div>

</div>
</div>


<style>
  .col-md-4 {
    padding: 0;
    margin: 0;
  }

  .col-md-8 {
    padding: 0;
    margin: 0;
  }
</style>