config/routes.rb
Rails.application.routes.draw do
  
  resources :replies, except: [:index]
  resources :comments, except: [:index], path: 'discussion'
  devise_for :users
  resources :features, except: [:index]
  root 'videos#index'
  resources :artists
  resources :videos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	is_impressionable
	belongs_to :video
	belongs_to :user
	has_many :replies

	def count
    	"#{self.impressionist_count + self.video.impressionist_count }".length
    end

    def impression
    	(self.impressionist_count + self.video.impressionist_count).to_s
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  impressionist action: [:show]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @comments = Comment.all
  end


  def show

    set_meta_tags title: @comment.video.title,
              reverse: true,
              description: @comment.body,
              keywords: 'discussion, forum, comments'

  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to video_path(@comment.video_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to video_path(@comment.video_id), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to video_path(@comment.video_id), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:video_id, :user_id, :body, :current_duration)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :video_id, id: :comment_video_id, type: 'hidden' %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.trix_editor :body, id: :comment_body %>
  </div>


  <div class="actions text-align-right">
    <%= form.submit 'Post Comment', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="container">

	<h1>Editing Comment</h1>

	<%= render 'form', comment: @comment %>

	<%= link_to 'Show', @comment %> |
	<%= link_to 'Back', comments_path %>

</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th>User</th>
      <th>Body</th>
      <th>Current duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.video %></td>
        <td><%= comment.user %></td>
        <td><%= comment.body %></td>
        <td><%= comment.current_duration %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="container">
	
	<h1>New Comment</h1>

	<%= render 'form', comment: @comment %>

	<%= link_to 'Back', comments_path %>


</div>

app/views/comments/show.html.erb
<div class="comments_wrapper">

	<div class="container">

		<div class="row">
			<div class="col-md-8">


				<div class="card">
				  <div class="card-body">
				    <h5 class="card-title">
				    	<%= @comment.video.title %>	
			    	</h5>
				    <h6 class="card-subtitle mb-2 text-muted">
					    Uploaded <%= time_ago_in_words(@comment.video.created_at )%> |
					    <% if @comment.video.count >= 4 %>

	                      <%= @comment.video.impression[0...-3] %> K

	                    <% elsif @comment.video.count >= 7 %>

	                      <%= @comment.video.impression[0...-6] %> M
	                    
	                    <% end %>

	                    <% if @comment.video.count < 4 %>
	                      <%= @comment.video.impressionist_count %>
	                    <% end %> Views

					</h6>
				    <p class="card-text">
				    	<%= @comment.video.description.html_safe %>
				    </p>
				    <a href="<%= video_path(@comment.video.id) %>" class="card-link btn btn-primary">
					   <i class="fas fa-video"></i> Watch Video
					</a>
				    <!-- <a href="#" class="card-link">Another link</a> -->
				  </div>
				</div>

				<br>



				<div class="comment_item">

					<div class="comment_user_info">
						<div class="comment_avatar" style="background-image: url('https://vignette.wikia.nocookie.net/baki/images/c/cd/Jack_Hammer.PNG/revision/latest?cb=20160924195915');"></div>
					</div>
					<div class="commnent_body">

						<div class="email_user">
							<%= @comment.user.email %> <br>
							<p class="time_ago_comment">
							<%= time_ago_in_words(@comment.created_at)%>
							</p>
						</div>
						<%= @comment.body.html_safe %> <br>
						<%= link_to 'Edit', edit_comment_path(@comment.id) %>
						<br>


						<div class="comment_item">
							<% @comment.replies.each do |r| %>
							 <br>
							


							<div class="comment_user_info">
								<div class="comment_avatar" style="background-image: url('https://vignette.wikia.nocookie.net/baki/images/c/cd/Jack_Hammer.PNG/revision/latest?cb=20160924195915');"></div>
							</div>
							<div class="commnent_body">

								<div class="email_user">
									<%= r.user.email %> <br>
									<p class="time_ago_comment">
									<%= time_ago_in_words(r.created_at)%>
									</p>
								</div>
								<%= r.body.html_safe %>
								<%= link_to 'Edit', edit_reply_path(r) %>
								<br>	
							</div>


							<% end %>

							<br><br>


							<%= form_for Reply.new do |reply| %>
								<%= reply.text_field :comment_id, value: @comment.id, type: 'hidden' %>
								<%= reply.trix_editor :body %>
								<div class="text-align-right">
									<%= reply.button "Reply", class: 'btn btn-success', onclick: "videoTimer()" %>
								</div>
							<% end %>
						</div>


					</div>

				</div>

			</div>
			<div class="col">


				<div class="calculator" >
				  <div class="calculator-body">
				    <h5 class="calculator-title">
				    	statistics
				    </h5>
				  </div>
				</div>

				<div class="calculator bg-light" >
				  <div class="calculator-body">
					<div class="calculator-text">
				    	<div class="row">
				    		<div class="col">
				    			<h6>Replies</h6>
					    		<h3><%= @comment.replies.count %></h3>
					    	</div>
				    		<div class="col">
				    			<h6>Views</h6>
					    		<h3>
					    			<% if @comment.count >= 4 %>
				                      <%= @comment.impression[0...-3] %> K
				                    <% elsif @comment.count >= 7 %>
				                      <%= @comment.impression[0...-6] %> M
				                    <% end %>
				                    <% if @comment.count < 4 %>
				                      <%= @comment.impression %>
				                    <% end %>
					    		</h3>
					    	</div>
				    	</div>
					</div>
				</div>
				</div>

				

			</div>

		</div>


	</div>



</div>