config/routes.rb
Rails.application.routes.draw do
  
  resources :replies, except: [:index]
  resources :comments, except: [:index], path: 'discussion'
  devise_for :users
  resources :features, except: [:index]
  root 'videos#index'
  resources :artists
  resources :videos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
    is_impressionable
    has_attached_file :media, :styles => {
        # :medium => { :geometry => "640x480", :format => 'flv' },
        :thumb => { :geometry => "600x600>", :format => 'jpg', :time => 10 }
      }, :processors => [:transcoder]
    
    validates_attachment_content_type :media, :content_type => /\Avideo\/.*\Z/      

    has_many :features, dependent: :delete_all
    has_many :comments, dependent: :delete_all


    def count
    	"#{self.impressionist_count}".length
    end

    def impression
    	(self.impressionist_count).to_s
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  impressionist action: [:show]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @videos = Video.all
  end

  def show
    @videos = Video.where('id != ?', @video.id).order("RANDOM()")
    @comments = Comment.where(video_id: @video.id).order("created_at DESC")

    set_meta_tags title: @video.title,
              reverse: true,
              description: @video.description,
              keywords: 'watch, video, comment'
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, :description, :duration, :media)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_comments.html.erb
<!-- <button onclick="videoTimer()">Click me</button> -->

<% if user_signed_in? %>
	<%=form_for Comment.new do |f|%>

	<div class="form-group comments_form">

		<div class="row">
			<div class="col-md-1">
				<div class="user_avatar_circle"></div>
			</div>
			<div class="col">
				<%= f.text_field :video_id, value: @video.id, type: 'hidden' %>
				<%= f.text_field :current_duration, id: :current_duration, type: 'hidden' %>
				<%= f.trix_editor :body, class: 'form-control' %>
				<div class="row">
					<div class="col"> </div>
					<div class="col text-align-right">
						<%= f.button "Post Comment", class: 'btn btn-success', onclick: "videoTimer()" %>
					</div>
				</div>
			</div>

		</div>

	</div>



	<% end %>

<% end %>

<div class="comments_list">
	
	<% @comments.each do |comment| %>
		<div class="comment_item">
			<div class="comment_user_info">
				<div class="comment_avatar" style="background-image: url('https://vignette.wikia.nocookie.net/baki/images/c/cd/Jack_Hammer.PNG/revision/latest?cb=20160924195915');"></div>
			</div>
			<div class="commnent_body">

				<div class="email_user">
					<%= comment.user.email %> <br>
					<p class="time_ago_comment">
					<%= time_ago_in_words(comment.created_at)%>
					</p>
				</div>

				<%= comment.body.html_safe %>
				<br>	
				<%= link_to 'Edit', edit_comment_path(comment) %>
				<%= link_to 'Delete', comment, method: :delete %>	

				<hr>

				<div class="comment_item">
					<% comment.replies.each do |r| %>
					 <br>
					
					<div class="comment_user_info">
						<div class="comment_avatar" style="background-image: url('https://vignette.wikia.nocookie.net/baki/images/c/cd/Jack_Hammer.PNG/revision/latest?cb=20160924195915');"></div>
					</div>
					<div class="commnent_body">

						<div class="email_user">
							<%= r.user.email %> <br>
							<p class="time_ago_comment">
							<%= time_ago_in_words(r.created_at)%>
							</p>
						</div>
						<%= r.body.html_safe %>
						<%= link_to 'Edit', edit_reply_path(r) %>
						<%= link_to 'Delete', r, method: :delete %>	
						<br>	
					</div>
					<% end %>

					<button class="btn btn-light fw" onclick="replies();">Reply</button>
					
				</div>


				<br>
				<br>


				<% if user_signed_in? %>
					<div class="replies hidden">
						<%= form_for Reply.new do |reply| %>
							<%= reply.text_field :comment_id, value: comment.id, type: 'hidden' %>
							<%= reply.trix_editor :body %>
							<div class="text-align-right">
								<%= reply.button "Reply", class: 'btn btn-success', onclick: "videoTimer()" %>
							</div>
							
							<script>
								var id = "reply"+<%= comment.id %>;
								function replies() {
									console.log(id);
									$('.replies').addClass(id).removeClass("hidden");
								};
							</script>
						<% end %>
						
					</div>
				<% end %>

			</div>
		</div>
	<% end %>
</div>

<!-- <div class="spanSpace"></div> -->

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :media %>
    <%= form.file_field :media %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :video_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.trix_editor :description, id: :video_description %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration, id: :video_duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/_navbar.html.erb
<div class="navPlaceholder"></div>
<!-- nav not signed in -->

<nav class="mainNavbar">
  <div class="row">
    <div class="col-md-2 nav_first_item">
      <button class="dropdownMenu">
        <i class="fa fa-bars"></i>
      </button>
      
      <a href="<%= root_path %>"><div class="brand"></div></a>
    </div>
    <div class="col">
      <div class="input-group">
          <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
    </div>

    <div class="col-md-4 align-right nav_last_item">

      <% if user_signed_in? %>

        <div class="dropdown">
          <button class="btn btn-avatar-round" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

          </button>
          

          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">New around here? Sign up</a>
            <a class="dropdown-item" href="#">Forgot password?</a>
          </div>

        </div>

      <% else %>

        <div class="dropdown drop_nav_image">
          <button class="sign_in btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Login
          </button>
          

          <div class="dropdown-menu">
            <form class="px-4 py-3">
              <div class="form-group">
                <label for="exampleDropdownFormEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleDropdownFormEmail1" placeholder="email@example.com">
              </div>
              <div class="form-group">
                <label for="exampleDropdownFormPassword1">Password</label>
                <input type="password" class="form-control" id="exampleDropdownFormPassword1" placeholder="Password">
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="dropdownCheck">
                <label class="form-check-label" for="dropdownCheck">
                  Remember me
                </label>
              </div>
              <button type="submit" class="btn btn-primary">Sign in</button>
            </form>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">New around here? Sign up</a>
            <a class="dropdown-item" href="#">Forgot password?</a>
          </div>

        </div>


        <!-- sign Up button -->

        <div class="dropdown drop_nav_image">
          <button class="sign_up btn btn-primary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sign Up
          </button>
          

          <div class="dropdown-menu">
            <form class="px-4 py-3">
              <div class="form-group">
                <label for="exampleDropdownFormEmail1">HELLO</label>
                <input type="email" class="form-control" id="exampleDropdownFormEmail1" placeholder="email@example.com">
              </div>
              <div class="form-group">
                <label for="exampleDropdownFormPassword1">Password</label>
                <input type="password" class="form-control" id="exampleDropdownFormPassword1" placeholder="Password">
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="dropdownCheck">
                <label class="form-check-label" for="dropdownCheck">
                  Remember me
                </label>
              </div>
              <button type="submit" class="btn btn-primary">Sign in</button>
            </form>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">New around here? Sign up</a>
            <a class="dropdown-item" href="#">Forgot password?</a>
          </div>

        </div>

        <!-- <button class="sign_up btn btn-primary">Sign Up</button> -->
      <% end %>


      


    </div>
  </div>
  
  

  

</nav>


<!-- signed in nav -->

app/views/videos/_videoplayer.html.erb
<div class="">
<!-- add this class to the div above videoSpace -->
    <div class="videoplayer_container uhPlayer">
        

        <video autoplay="autoplay" id="videoPlayer">
            <source src="<%=  @video.media.url%>"></source>
        </video>
        <!-- , controls: true -->

        <div class="vControllers" style="display: hidden" >
            <div class="container-fuild">

                <div class="skeebar_container">
                    <div class="download_progress">
                        <div class="current_progress">
                        </div>
                    </div>
                    
                </div>

                <div class="row">
                    <div class="col">
                        <button class="playPause btn_plyr pauseIcon fll mr-2"></button>
                        <button class="loopBtn loopIcon btn_plyr fll mr-2" ></button>                    
                        <button class="muteBtn mutedIcon btn_plyr fll mr-2"></button>
                        <div class="volumelevels">
                            <button class="volume-10 volBtn"></button>
                            <button class="volume-20 volBtn"></button>
                            <button class="volume-40 volBtn"></button>
                            <button class="volume-60 volBtn"></button>
                            <button class="volume-80 volBtn"></button>
                            <button class="volume-100 volBtn"></button>
                            
                            
                                                    
                        </div>
                    </div>
                    <div class="col text-align-right ml-2">
                        <div class="timers">
                                <label id="duration">00:00</label> |
                                <label id="current-time">00:00</label>
                        </div>
                        <button class="fullscreenIcon btn_plyr flr ml-2" id="btnFullscreen"></button>                                        
                        <button class="settings settingsIcon btn_plyr flr ml-2"></button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<button onclick="fullscreenToggle();">
    full screen
</button>

<script>
    vid = document.querySelector("#videoPlayer");    
</script>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="container">

  <% @videos.each do |video| %>
    <div class="video_card">
      <a href="<%= video_path(video) %>">
        <div class="video_thumb" style=" background-image: url(<%= video.media.url(:thumb) %>); ">
          <span class="video_duration badge badge-dark">
            <%= video.duration %>
          </span>
        </div>
      </a>
      <div class="video_info">
        <div class="container">
          <div class="video_title">
            <%= truncate(video.title, length: 40) %> 
          </div>

          <div class="row video_stats">
            <div class="col">
              <%= video.impressions.count %>
            </div>
            <div class="col bl-1">
              <%= time_ago_in_words(video.created_at) %>
            </div>        
          </div>

        </div>
      
      </div>

      
      <%#= link_to 'Show', video %>
      <%#= link_to 'Edit', edit_video_path(video) %>
      <%#= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </div>
  <% end %>

</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">

            <div class="videoContainer">
              <%= render 'videos/videoplayer' %>
            </div>

            <div class="container">
              <div class="row">
                <div class="col-md-10">
                  <h2 class="video_title">
                    <%= @video.title %>
                  </h2>
                  <h6 class="time_ago_video"><%= time_ago_in_words(@video.created_at) %></h6>

                </div>
                <div class="col-md-2 text-align-right">
                  <h2 class="views_item">
                    <% if @video.count >= 4 %>

                      <%= @video.impression[0...-3] %> K

                    <% elsif @video.count >= 7 %>

                      <%= @video.impression[0...-6] %> M
                    
                    <% end %>

                    <% if @video.count < 4 %>
                      <%= @video.impressionist_count %>
                    <% end %>

                  </h2>

                  Views
                  
                </div>
              </div>

              <p><%= @video.description.html_safe %></p>

              <%#= link_to 'Edit', edit_video_path(@video) %> 
              <!-- | -->
              <%#= link_to 'Back', videos_path %>

              <br><br>


              <div class="features">                

              <% @video.features.each do |ft| %>
                <a href="<%= artist_path(ft.artist)%>">

                  <div class="avatar_features"  style=" background-image: url(<%= ft.artist.avatar.url(:small)%>);">

                    <div class="verification"></div>
                    
                  </div>
                  <%#= link_to 'Destroy', ft, method: :delete %>
                </a>
              <% end %>
              </div>


            </div>


            <div class="form">
              <br>
              <div class="container">

                <!-- Button trigger modal -->
                <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newfeatures">
                  Add New Feature
                </button> -->

                <!-- Modal -->
                <div class="modal fade" id="newfeatures" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <%= form_for Feature.new do |f|%>
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        

                        <div>
                          <%= f.text_field :video_id, value: @video.id, type: 'hidden' %> 
                        </div>

                        <div>
                          <%= f.label :artist_id %>
                          <%= f.select(:artist_id, Artist.select) %> 
                        </div>


                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <%= f.submit 'save', class: "btn btn-primary" %>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                
                    
                  
                </div>
                <br>
            </div>


            <div class="comments">

              <div class="container">
                <h6><%= @video.comments.size %> Comments <i class="far fa-comment-alt"></i> </h6>
                <br><br>
                <%= render 'videos/comments' %>

              </div>
              
            </div>

        </div>

        <div class="col-md-4">

          <% @videos.each do |v| %>

          <div class="video_side_thumbs">
            <a href="<%= video_path(v)%>">
              <div class="thumbs" style=" background-image: url(<%= v.media.url(:thumb)%>);">
                <span class="duration badge badge-dark">
                  <%= v.duration %>
                </span>
              </div>
              <div class="vsinfo">
                <p class="title"><%= truncate(v.title, length: 40 )%></p>
                <p class="views">
                  <%= v.impressionist_count %> Views
                </p>
              </div>
            </a>
            
          </div>
          <% end %>
        
        </div>

    </div>
</div>